// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsFfvtFlZnOrKshfmaNpFiNkch2eipYnE',
    appId: '1:332283503136:web:155c2261ec07c5ac6f1245',
    messagingSenderId: '332283503136',
    projectId: 'navin-supermarkett',
    authDomain: 'navin-supermarkett.firebaseapp.com',
    storageBucket: 'navin-supermarkett.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfJINkkKJmx1zA862RwiJcP9ZVJ7LfGU4',
    appId: '1:332283503136:android:e9ec080e1f9f48fd6f1245',
    messagingSenderId: '332283503136',
    projectId: 'navin-supermarkett',
    storageBucket: 'navin-supermarkett.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3bkT6ha_yC9gtDFGPh81264rxNdYZf6A',
    appId: '1:332283503136:ios:e1b7b302e49194076f1245',
    messagingSenderId: '332283503136',
    projectId: 'navin-supermarkett',
    storageBucket: 'navin-supermarkett.firebasestorage.app',
    iosBundleId: 'com.example.exemplPr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3bkT6ha_yC9gtDFGPh81264rxNdYZf6A',
    appId: '1:332283503136:ios:e1b7b302e49194076f1245',
    messagingSenderId: '332283503136',
    projectId: 'navin-supermarkett',
    storageBucket: 'navin-supermarkett.firebasestorage.app',
    iosBundleId: 'com.example.exemplPr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsFfvtFlZnOrKshfmaNpFiNkch2eipYnE',
    appId: '1:332283503136:web:bf28afb321b844fb6f1245',
    messagingSenderId: '332283503136',
    projectId: 'navin-supermarkett',
    authDomain: 'navin-supermarkett.firebaseapp.com',
    storageBucket: 'navin-supermarkett.firebasestorage.app',
  );
}
